NAME = display_file
FLAGS = -Wall -Wextra -Werror
FILES = main.c
OPTION = -o

all : $(NAME)

$(NAME) :
	@gcc $(FLAGS) $(FILES) $(OPTION) $(NAME)

clean :
	@export a

fclean : clean
	@rm -rf $(NAME)

re : fclean $(NAME)
